name: Build and Push to ECR

on:
  push:
    branches: main
  merge_group:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      API_REPO_NAME: rankbang-dev
      cluster_name: rankbang-dev-Cluster
      region: us-east-1
      env: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: {{ env.API_REPO_NAME }}

      - name: Build Docker Image
        run: docker build -t  ${{ env.API_REPO_NAME }} .

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Docker Image
        run: docker tag ${{ env.API_REPO_NAME }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ env.API_REPO_NAME }}:${{ github.sha }}

      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.API_REPO_NAME }}:${{ github.sha }}


      # - name: Deploy API Helm Chart
      #   run: |
      #     helm upgrade --install rank_bang_chart ./api_helm_chart \
      #     -f ./rank_bang_chart/values.yaml \
      #     --set image.repository="${{ steps.login-ecr.outputs.registry }}/${{ env.API_REPO_NAME }}:${{ github.sha }}" \
      #     --force
      #     rm -rf ~/.kube
